import { MainDashboardContainer, Column } from './MainDashboard.styled';

export const MainDashboard = () => {
  return (
    <MainDashboardContainer>
      <Column>
        <div>Title</div>
        <div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
        </div>
        <div>BUTTON</div>
      </Column>
      <Column>
        <div>Title</div>
        <div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
        </div>
        <div>BUTTON</div>
      </Column>
      <Column>
        <div>Title</div>
        <div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
        </div>
        <div>BUTTON</div>
      </Column>
      <Column>
        <div>Title</div>
        <div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
        </div>
        <div>BUTTON</div>
      </Column>
      <Column>
        <div>Title</div>
        <div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
        </div>
        <div>BUTTON</div>
      </Column>
      <Column>
        <div>Title</div>
        <div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
          <div>Card</div>
        </div>
        <div>BUTTON</div>
      </Column>
    </MainDashboardContainer>
  );
};
